services:
  - type: web
    name: amazon-geotagger
    env: python
    buildCommand: echo "No build step"
    startCommand: python main.py
    plan: free
    envVars:
      - key: REPORTS_CSV_PATH
        value: /var/data/illegal_mining_reports.csv
    disk:
      name: reports-data
      mountPath: /var/data
      sizeGB: 1
